[project]
name = "lyrics-show"
version = "0.1.0"
requires-python = ">=3.10"
license = { text = "GPL-3.0-or-later" }
dependencies = [
    "netease-cloudmusic-detector>=2.0.6",
    "pyqt5==5.15.10",
    "pyqt5-qt5==5.15.2",
    "pywin32>=312",
    "httpx>=0.27.0",
    "qasync>=0.28.0",
    "PyQt-Fluent-Widgets>=1.7.9",
    "websocket-client>=1.9.0",
    "winrt-runtime>=3.2.1",
    "winrt-windows-foundation>=3.2.1",
    "winrt-windows-foundation-collections>=3.2.1",
    "winrt-windows-media-control>=3.2.1",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "nuitka>=4.1.3",
    "pyinstaller>=6.22.0",
]
